In [0]:
%pip install openpyxl

Looking in indexes: [REDACTED]
Requirement already satisfied: openpyxl in /local_disk0/.ephemeral_nfs/envs/pythonEnv-61932c9b-359c-4903-a7fa-45644377d294/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /local_disk0/.ephemeral_nfs/envs/pythonEnv-61932c9b-359c-4903-a7fa-45644377d294/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
import pandas as pd
import openpyxl
import requests
import re #regex

In [0]:
# Path to download the API
path_munic = "https://ftp.ibge.gov.br/Perfil_Municipios/2024/Base_de_Dados/Base_MUNIC_2024_20251107.xlsx"
munic_file = "Base_MUNIC_2024.xlsx"

In [0]:
# Do the request to the IBGE APIs
file = requests.get(path_munic)

In [0]:
# Returns a exception if occur a error on the request
file.raise_for_status()

In [0]:
with open(munic_file, "wb") as f:
    f.write(file.content)

Workbook (wb) = the complete file

Worksheet (ws) = the individual tabbed pages inside the workbook

In [0]:
# Inspect available sheets
wb = openpyxl.load_workbook(munic_file, read_only=True)
print("Available sheets:", wb.sheetnames)

Available sheets: ['Dicionário', 'Recursos humanos', 'Informática e comunicação', 'Governanca', 'Habitacao', 'Transporte e mobilidade urbana', 'Agropecuária', 'Gestão migratória', 'Igualdade racial', 'Evento climático RS']

In [0]:
type(munic_file)

str

In [0]:
# Take the specific worksheet that we want
info_ws = wb["Informática e comunicação"]

In [0]:
for row in info_ws.iter_rows(max_row=5, values_only=True):
  print(row)

('Cod Munic', 'Uf', 'Cod Uf', 'Desc Mun', 'Populacao', 'Faixa_populacao', 'Regiao', 'Mtic011', 'Mtic012', 'Mtic013', 'Mtic014', 'Mtic015', 'Mtic016', 'Mtic017', 'Mtic018', 'Mtic04', 'Mtic06', 'Mtic071', 'Mtic072', 'Mtic073', 'Mtic074', 'Mtic075', 'Mtic076', 'Mtic077', 'Mtic078', 'Mtic08', 'Mtic091', 'Mtic092', 'Mtic093', 'Mtic10', 'Mtic11', 'Mtic12a1', 'Mtic12a2', 'Mtic12a3', 'Mtic12a4', 'Mtic12a5', 'Mtic12a6', 'Mtic12a7', 'Mtic12a8', 'Mtic12b1', 'Mtic12b2', 'Mtic12b3', 'Mtic12b4', 'Mtic12b5', 'Mtic12b6', 'Mtic12b7', 'Mtic12b8', 'Mtic12b9', 'Mtic12b10', 'Mtic12b11', 'Mtic12b12', 'Mtic12b13', 'Mtic12b14', 'Mtic131', 'Mtic132', 'Mtic133', 'Mtic134', 'Mtic135', 'Mtic136', 'Mtic137', 'Mtic138', 'Mtic139', 'Mtic141', 'Mtic142', 'Mtic143', 'Mtic144', 'Mtic145', 'Mtic146', 'Mtic15', 'Mtic161', 'Mtic162', 'Mtic163', 'Mtic164', 'Mtic165', 'Mtic166', 'Mtic167', 'Mtic171', 'Mtic172', 'Mtic173', 'Mtic174', 'Mtic175', 'Mtic176', 'Mtic181', 'Mtic182', 'Mtic183', 'Mtic184', 'Mtic185', 'Mtic186', 'Mtic18a1', 'Mtic18a2', 'Mtic18a3', 'Mtic18a4', 'Mtic18a5', 'Mtic18a6', 'Mtic19', 'Mtic201', 'Mtic202', 'Mtic203', 'Mtic204', 'Mtic205', 'Mtic206', 'Mtic211', 'Mtic212', 'Mtic213', 'Mtic214', 'Mtic215', 'Mtic216', 'Mtic217', 'Mtic22', 'Mtic23', 'Mtic241', 'Mtic242', 'Mtic2421', 'Mtic243', 'Mtic2431', 'Mtic244', 'Mtic251', 'Mtic2511', 'Mtic2512', 'Mtic2513', 'Mtic2514', 'Mtic252', 'Mtic2521', 'Mtic2522', 'Mtic2523', 'Mtic2524', 'Mtic253', 'Mtic2531', 'Mtic2532', 'Mtic2533', 'Mtic2534', 'Mtic254', 'Mtic2541', 'Mtic2542', 'Mtic2543', 'Mtic2544', 'Mtic255', 'Mtic261', 'Mtic262', 'Mtic263', 'Mtic264', 'Mtic265', 'Mtic266', 'Mtic271', 'Mtic272', 'Mtic273', 'Mtic281', 'Mtic282', 'Mtic283', 'Mtic284', 'Mtic285', 'Mtic286', 'Mtic287', 'Mtic288', 'Mtic289', 'Mtic29', 'Mtic30', 'Mtic31', 'Mtic321', 'Mtic322', 'Mtic323', 'Mtic324', 'Mtic325', 'Mtic326', 'Mtic327', 'Mtic328', 'Mtic33', 'Mtic331', 'Mtic341', 'Mtic342', 'Mtic343', 'Mtic344', 'Mtic345', 'Mtic346', 'Mtic347', 'Mtic348', 'Mtic349', 'Mtic35', 'Mtic3511', 'Mtic3512', 'Mtic3513', 'Mtic3514', 'Mtic3515', 'Mtic3516', 'Mtic3517', 'Mtic3518', 'Mtic3519', 'Mtic35110', 'Mtic35111', 'Mtic361', 'Mtic362', 'Mtic363', 'Mtic364', 'Mtic365', 'Mtic366', 'Mtic367', 'Mtic368', 'Mtic37', 'Mtic381', 'Mtic382', 'Mtic383', 'Mtic384', 'Mtic385', 'Mtic386', 'Mtic387')
(1100015, 'RO', 11, 'Alta Floresta DOeste', 22853, '4 - 20001 até 50000', '1 - Norte', 'Não', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Via cabo ou fibra ótica', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', 'Não', 'Não', 'Não', 'Sim', 'Ativa', 'WWW.ALTAFLORESTA.RO.GOV.BR', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Diariamente', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Sim', 'Gratuito', 'Não', 'Sim', 'Parte', 'Não', '-', 'Não', 'Não', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Modelo próprio de acessibilidade digital', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não')
(1100023, 'RO', 11, 'Ariquemes', 108573, '6 - 100001 até 500000', '1 - Norte', 'Não', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Via cabo ou fibra ótica', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Ativa', 'WWW.ARIQUEMES.RO.GOV.BR', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Diariamente', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Gratuito', 'Não', 'Não', '-', 'Não', '-', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Não', '-', '-', '-', '-', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', '-', '-', '-', '-', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Modelo global de acessibilidade digital (WCAG/WAI)', 'Sim', 'DEPARTAMENTO DE COMUNICAÇÃO', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', '-', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não')
(1100031, 'RO', 11, 'Cabixi', 5690, '2 - 5001 até 10000', '1 - Norte', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Via cabo ou fibra ótica', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', 'Sim', 'Não', 'Não', 'Sim', 'Ativa', 'WWW.CABIXI.RO.GOV.BR', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', '-', '-', '-', '-', '-', '-', '-', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não há qualquer modelo de acessibilidade digital', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Não', '-', '-', '-', '-', '-', '-', 'Sim')
(1100049, 'RO', 11, 'Cacoal', 97637, '5 - 50001 até 100000', '1 - Norte', 'Não', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Via cabo ou fibra ótica', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Ativa', 'WWW.CACOAL.RO.GOV.BR', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Pelo menos uma vez por semana', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Sim', 'Gratuito', 'Não', 'Sim', 'Parte', 'Sim', 'Parte', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', '-', '-', '-', '-', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Modelo próprio de acessibilidade digital', 'Sim', 'ACESSORIA DE COMUNICAÇÃO ', 'Não', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', '-', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não')

## Convert the Worksheets to Dataframe

- "Informatica e Comunicação", Governance and Dicionary worksheets

In [0]:
df_dict = pd.read_excel("Base_MUNIC_2024.xlsx", sheet_name="Dicionário", header=None)

In [0]:
df_info_ws = pd.read_excel(
    "Base_MUNIC_2024.xlsx",
    sheet_name="Informática e comunicação"
)

df_governance_ws = pd.read_excel(
    "Base_MUNIC_2024.xlsx",
    sheet_name="Governanca"
)

In [0]:
df_data = pd.merge(df_info_ws, df_governance_ws, on="Cod Munic", how="inner")

In [0]:
df_dict.head(50)

                                                    0  ...            5
0                                                 NaN  ...          NaN
1                                   Temas disponíveis  ...     variável
2                                                 NaN  ...          NaN
3                     1. RECURSOS HUMANOS POR VÍNCULO  ...  título link
4                        2. INFORMÁTICA E COMUNICAÇÃO  ...  título link
5                                       3. GOVERNANÇA  ...  título link
6                                        4. HABITAÇÃO  ...  título link
7                   5. TRANSPORTE E MOBILIDADE URBANA  ...  título link
8                                     6. AGROPECUÁRIA  ...  título link
9                7. INSTRUMENTOS DE GESTÃO MIGRATÓRIA  ...  título link
10                                8. IGUALDADE RACIAL  ...  título link
11              9. EVENTO CLIMÁTICO RIO GRANDE DO SUL  ...  título link
12                                                NaN  ...          NaN
13                                Código do Município  ...       CodMun
14                     Código da Unidade da Federação  ...           UF
15                      Sigla da Unidade da Federação  ...       Cod UF
16                                  Nome do Município  ...          Mun
17  População dos Municípios publicada no DOU em 2...  ...       PopMun
18                                 Faixa da população  ...    Faixa_pop
19                                      Grande Região  ...       Regiao
20  *Estimativas da população residente nos municí...  ...          NaN
21                                                NaN  ...          NaN
22                    1. RECURSOS HUMANOS POR VÍNCULO  ...          NaN
23  1.1 Composição do quadro de pessoal da adminis...  ...          NaN
24  1.2 Composição do quadro de pessoal da adminis...  ...          NaN
25  1.3 Identificação dos servidores por cor/raça ...  ...          NaN
26                                                NaN  ...          NaN
27  Fonte: IBGE, Pesquisa de Informações Básicas M...  ...          NaN
28                                                NaN  ...          NaN
29                    1. RECURSOS HUMANOS POR VÍNCULO  ...          NaN
30  1.1 Composição do quadro de pessoal da adminis...  ...          NaN
31                                                NaN  ...     MREH0111
32                                                NaN  ...     MREH0112
33                                                NaN  ...     MREH0113
34                                                NaN  ...     MREH0114
35                                                NaN  ...     MREH0115
36                                          Total (1)  ...     MREH0116
37                                                NaN  ...          NaN
38  Fonte: IBGE, Pesquisa de Informações Básicas M...  ...          NaN
39        (1) Inclusive os sem declaração de vínculo.  ...          NaN
40              (*) Não sabe informar o quantitativo.  ...          NaN
41  Recusa: o município não respondeu o questionár...  ...          NaN
42    Não informou: quesito em branco no questionário  ...          NaN
43                                                NaN  ...          NaN
44  1.2 Composição do quadro de pessoal da adminis...  ...          NaN
45                Administração indireta - existência  ...       MREH02
46                                                NaN  ...      MREH031
47                                                NaN  ...      MREH032
48                                                NaN  ...      MREH033
49                                                NaN  ...      MREH034

[50 rows x 6 columns]

## Extract the Meaning of the Code Variables on the Sheets

- It´s keeped on the df_metabase_info_ws on the final of this section

In [0]:
def obtain_filled_cells(row):
    # Basically catch the values in a row from the dictionary sheet, to retire the columns vacances
    filled_cells = [str(val).strip() for val in row if pd.notna(val) and str(val).strip() != '']

    return filled_cells


def extract_var_code_meaning(row, var_pattern_list):
  """
    Extracts variable codes and their corresponding survey descriptions
    from a raw IBGE MUNIC dictionary row.

    Parameters:
        row (pd.Series): A single row from the unformatted dictionary sheet.
        var_pattern (str): The thematic variable prefix to match (e.g., 'MTIC', 'MGOV', 'MREH').

    Returns:
        dict: {'cod_variable': <str>, 'meaning': <str>} if a code matching the pattern is found,
              otherwise None.
    """

  # It´s used to save the pattern matched on the row using regex
  code_matches = list()

  filled_cells = obtain_filled_cells(row)

  # Verify if the row has values or not
  if not filled_cells:
      return None

  # Create the Regex Expressions
  regex_expr_list = [rf'^{pattern}\d+' for pattern in var_pattern_list]


  # Match if any cell have some pattern codes and add it in code_matches list
  for re_expr in regex_expr_list:
      for val in filled_cells:
        if re.match(re_expr, val, flags=re.IGNORECASE):
           code_matches.append(val)


  # If has any value with some of the code patterns
  if code_matches:
      cod_var = code_matches[0]

      # Find the description or what means of the MTIC code
      desc_cells = [val for val in filled_cells if val != cod_var]

      # If has one string value, get it. If has more, join the them. If doesn´t have, return None meaning to that code
      if desc_cells:
        if len(desc_cells) == 1:
          code_meaning = desc_cells[0]
        else:
          code_meaning = " - ".join(desc_cells) if desc_cells else None

      return {"cod_variable": cod_var, "meaning": code_meaning}

  # Else, returns None
  return None

In [0]:
# Get the meaning of the codes in the "Dicionario" worksheet (Ws)

code_patterns = ['MTIC', 'MGOV']
ws_meta_vars = [res for res in df_dict.apply(extract_var_code_meaning, axis=1, args=(code_patterns,)) if res is not None]

In [0]:
ws_meta_vars

[{'cod_variable': 'MTIC011', 'meaning': 'Correio'},
 {'cod_variable': 'MTIC012', 'meaning': 'Jornais'},
 {'cod_variable': 'MTIC013', 'meaning': 'Websites'},
 {'cod_variable': 'MTIC014', 'meaning': 'WhatsApp'},
 {'cod_variable': 'MTIC015', 'meaning': 'Telefone'},
 {'cod_variable': 'MTIC016', 'meaning': 'Telefone exclusivo'},
 {'cod_variable': 'MTIC017', 'meaning': 'Outros'},
 {'cod_variable': 'MTIC018', 'meaning': 'Não disponibiliza'},
 {'cod_variable': 'MTIC04', 'meaning': 'Tipo de conexão com a internet'},
 {'cod_variable': 'MTIC06',
  'meaning': 'Estrutura organizacional para a área de Tecnologia da Informação e Comunicação (TIC) - existência'},
 {'cod_variable': 'MTIC071',
  'meaning': 'Funcionários efetivos da própria prefeitura'},
 {'cod_variable': 'MTIC072',
  'meaning': 'Servidores cedidos de outro órgão público'},
 {'cod_variable': 'MTIC073', 'meaning': 'Estagiários'},
 {'cod_variable': 'MTIC074',
  'meaning': 'Cargo(s) Comissionado(s) de livre nomeação'},
 {'cod_variable': 'MTIC075', 'meaning': 'Terceirizados'},
 {'cod_variable': 'MTIC076', 'meaning': 'Consultores'},
 {'cod_variable': 'MTIC077', 'meaning': 'Outros'},
 {'cod_variable': 'MTIC078', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC08',
  'meaning': 'Centro de Processamento de Dados (CPD) - existência'},
 {'cod_variable': 'MTIC09',
  'meaning': 'Foi desenvolvido software para atender necessidade específica da prefeitura nos últimos 12 meses'},
 {'cod_variable': 'MTIC091',
  'meaning': 'Sim, para funcionamento interno ou atendimento a servidores da prefeitura'},
 {'cod_variable': 'MTIC092', 'meaning': 'Sim, para atendimento à sociedade'},
 {'cod_variable': 'MTIC093', 'meaning': 'Não'},
 {'cod_variable': 'MTIC10',
  'meaning': 'A página da prefeitura na internet está'},
 {'cod_variable': 'MTIC12a',
  'meaning': 'Serviços informativos disponibilizados na página da internet'},
 {'cod_variable': 'MTIC12a1',
  'meaning': 'Serviços informativos do município e notícias'},
 {'cod_variable': 'MTIC12a2', 'meaning': 'Acesso a documentos e formulários'},
 {'cod_variable': 'MTIC12a3',
  'meaning': 'Informações gerais sobre licitações'},
 {'cod_variable': 'MTIC12a4', 'meaning': 'Diário oficial'},
 {'cod_variable': 'MTIC12a5', 'meaning': 'Legislação municipal'},
 {'cod_variable': 'MTIC12a6', 'meaning': 'Finanças públicas'},
 {'cod_variable': 'MTIC12a7', 'meaning': 'Concursos públicos'},
 {'cod_variable': 'MTIC12a8', 'meaning': 'Nenhum dos relacionados'},
 {'cod_variable': 'MTIC12b',
  'meaning': 'Serviços disponibilizados na página da internet'},
 {'cod_variable': 'MTIC12b1',
  'meaning': 'Ouvidoria e serviços de atendimento ao cidadão'},
 {'cod_variable': 'MTIC12b2',
  'meaning': 'Download de documentos ou formulários'},
 {'cod_variable': 'MTIC12b3',
  'meaning': 'Consulta a processos/acompanhamento de protocolos'},
 {'cod_variable': 'MTIC12b4', 'meaning': 'Consulta prévia'},
 {'cod_variable': 'MTIC12b5', 'meaning': 'Cadastramento de fornecedores'},
 {'cod_variable': 'MTIC12b6',
  'meaning': 'Emissão de certidão negativa de débito'},
 {'cod_variable': 'MTIC12b7', 'meaning': 'Emissão de alvará'},
 {'cod_variable': 'MTIC12b8', 'meaning': 'Emissão de Nota Fiscal Eletrônica'},
 {'cod_variable': 'MTIC12b9',
  'meaning': 'Matrícula escolar na rede pública online'},
 {'cod_variable': 'MTIC12b10',
  'meaning': 'Agendamento de consulta e exame na rede pública de saúde'},
 {'cod_variable': 'MTIC12b11',
  'meaning': 'Emissão de guia de pagamento de tributos'},
 {'cod_variable': 'MTIC12b12',
  'meaning': 'Emissão de documentos como licenças, certidões, permissões e outros documentos'},
 {'cod_variable': 'MTIC12b13',
  'meaning': 'Pesquisa de satisfação relacionada aos serviços prestados pela prefeitura'},
 {'cod_variable': 'MTIC12b14', 'meaning': 'Nenhum dos relacionados'},
 {'cod_variable': 'MTIC131', 'meaning': 'Facebook'},
 {'cod_variable': 'MTIC132', 'meaning': 'Instagram'},
 {'cod_variable': 'MTIC133', 'meaning': 'Youtube'},
 {'cod_variable': 'MTIC134', 'meaning': 'Vimeo'},
 {'cod_variable': 'MTIC135', 'meaning': 'Telegran'},
 {'cod_variable': 'MTIC136', 'meaning': 'Whatsapp'},
 {'cod_variable': 'MTIC137', 'meaning': 'Twiter'},
 {'cod_variable': 'MTIC138', 'meaning': 'Tik Tok'},
 {'cod_variable': 'MTIC139', 'meaning': 'Não possui'},
 {'cod_variable': 'MTIC141', 'meaning': 'Postar notícias sobre a prefeitura'},
 {'cod_variable': 'MTIC142',
  'meaning': 'Responder a comentários e dúvidas dos cidadãos'},
 {'cod_variable': 'MTIC143',
  'meaning': 'Realizar consulta pública ou enquete'},
 {'cod_variable': 'MTIC144', 'meaning': 'Divulgar serviços ou campanhas'},
 {'cod_variable': 'MTIC145', 'meaning': 'Não realizou nenhuma das atividades'},
 {'cod_variable': 'MTIC146', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC15',
  'meaning': 'Frequência da atualização do conteúdo rede sociais - em média'},
 {'cod_variable': 'MTIC161', 'meaning': 'Envio de sms para o cidadão'},
 {'cod_variable': 'MTIC162', 'meaning': 'Recebimento de sms do cidadão'},
 {'cod_variable': 'MTIC163',
  'meaning': 'Aplicativos criados pela prefeitura ou outros organismos'},
 {'cod_variable': 'MTIC164',
  'meaning': 'Aplicativos criados por outros organismos ou cidadãos a partir de informações ou dados disponibilizados pela prefeitura'},
 {'cod_variable': 'MTIC165',
  'meaning': 'Website adaptado para dispositivos móveis ou desenhado em versão mobile'},
 {'cod_variable': 'MTIC166',
  'meaning': 'Emitir boletos de tributos ou outras guias de pagamento'},
 {'cod_variable': 'MTIC167', 'meaning': 'Não disponibilizou'},
 {'cod_variable': 'MTIC171', 'meaning': 'Ligação telefônica'},
 {'cod_variable': 'MTIC172', 'meaning': 'Website da prefeitura'},
 {'cod_variable': 'MTIC173',
  'meaning': 'Outro website que não o da prefeitura'},
 {'cod_variable': 'MTIC174',
  'meaning': 'Aplicativo de celular da prefeitura ou do serviço'},
 {'cod_variable': 'MTIC175', 'meaning': 'Redes sociais'},
 {'cod_variable': 'MTIC176', 'meaning': 'Nenhuma das alternativas'},
 {'cod_variable': 'MTIC181', 'meaning': 'Ligação telefônica'},
 {'cod_variable': 'MTIC182', 'meaning': 'Website da prefeitura'},
 {'cod_variable': 'MTIC183',
  'meaning': 'Outro website que não o da prefeitura'},
 {'cod_variable': 'MTIC184',
  'meaning': 'Aplicativo de celular da prefeitura ou do serviço'},
 {'cod_variable': 'MTIC185', 'meaning': 'Redes sociais'},
 {'cod_variable': 'MTIC186', 'meaning': 'Nenhuma das alternativas'},
 {'cod_variable': 'MTIC18a1',
  'meaning': 'Cadastro de usuário específico por órgão ou serviço'},
 {'cod_variable': 'MTIC18a2',
  'meaning': 'Cadastro unificado para todos os serviços da prefeitura'},
 {'cod_variable': 'MTIC18a3',
  'meaning': 'Acesso a alguns serviços com a conta GOV.BR'},
 {'cod_variable': 'MTIC18a4',
  'meaning': 'Acesso a todos os serviços com a conta GOV.BR'},
 {'cod_variable': 'MTIC18a5', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC18a6',
  'meaning': 'Não existe autenticação para acessar os serviços pela internet'},
 {'cod_variable': 'MTIC19',
  'meaning': 'Desenvolve programa ou ação de inclusão digital'},
 {'cod_variable': 'MTIC201', 'meaning': 'Governo federal'},
 {'cod_variable': 'MTIC202', 'meaning': 'Governo do estado'},
 {'cod_variable': 'MTIC203', 'meaning': 'Outro município'},
 {'cod_variable': 'MTIC204', 'meaning': 'Iniciativa privada'},
 {'cod_variable': 'MTIC205', 'meaning': 'Outros'},
 {'cod_variable': 'MTIC206', 'meaning': 'Iniciativa exclusiva da prefeitura'},
 {'cod_variable': 'MTIC211',
  'meaning': 'Disponibilização de acesso público e gratuito à Internet através de centros de acesso público, como telecentros'},
 {'cod_variable': 'MTIC212',
  'meaning': 'Disponibilização de informações e serviços de órgãos públicos, em quiosque ou balcão informatizado'},
 {'cod_variable': 'MTIC213',
  'meaning': 'Estabelecimento de parcerias com doadores de equipamentos e prestadores de serviços nas áreas de informática e telecomunicações, a fim de promover o acesso à Internet e aos computadores aos indivíduos'},
 {'cod_variable': 'MTIC214',
  'meaning': 'Promoção de cursos de capacitação em informática para a população'},
 {'cod_variable': 'MTIC215',
  'meaning': 'Instalação de computadores na rede pública municipal de ensino com acesso à Internet para utilização de alunos e professores'},
 {'cod_variable': 'MTIC216',
  'meaning': 'Instalação de rede WI-FI nas escolas da rede pública municipal para acesso de professores e alunos'},
 {'cod_variable': 'MTIC217', 'meaning': 'Outras'},
 {'cod_variable': 'MTIC22',
  'meaning': 'Disponibiliza acesso por conexão wi-fi'},
 {'cod_variable': 'MTIC23',
  'meaning': 'O acesso de conexão wi-fi é gratuito e/ou cobrado'},
 {'cod_variable': 'MTIC24', 'meaning': 'A conexão Wi-Fi atende'},
 {'cod_variable': 'MTIC241', 'meaning': 'Todo o município'},
 {'cod_variable': 'MTIC242', 'meaning': 'Área urbana'},
 {'cod_variable': 'MTIC243', 'meaning': 'Área rural'},
 {'cod_variable': 'MTIC244', 'meaning': 'Algumas áreas específicas'},
 {'cod_variable': 'MTIC251',
  'meaning': 'Consulta pública on line para que cidadãos possam enviar contribuições para leis, orçamentos e planos'},
 {'cod_variable': 'MTIC2511', 'meaning': 'Website ou portal da prefeitura'},
 {'cod_variable': 'MTIC2512',
  'meaning': 'Website ou portal de outro órgão público'},
 {'cod_variable': 'MTIC2513', 'meaning': 'Redes sociais'},
 {'cod_variable': 'MTIC2514', 'meaning': 'Outro website ou portal'},
 {'cod_variable': 'MTIC252',
  'meaning': 'Grupos de discussão como fóruns ou comunidades pela internet'},
 {'cod_variable': 'MTIC2521', 'meaning': 'Website ou portal da prefeitura'},
 {'cod_variable': 'MTIC2522',
  'meaning': 'Website ou portal de outro órgão público'},
 {'cod_variable': 'MTIC2523', 'meaning': 'Redes sociais'},
 {'cod_variable': 'MTIC2524', 'meaning': 'Outro website ou portal'},
 {'cod_variable': 'MTIC253',
  'meaning': 'Enquete on line sobre assuntos de interesse da prefeitura'},
 {'cod_variable': 'MTIC2531', 'meaning': 'Website ou portal da prefeitura'},
 {'cod_variable': 'MTIC2532',
  'meaning': 'Website ou portal de outro órgão público'},
 {'cod_variable': 'MTIC2533', 'meaning': 'Redes sociais'},
 {'cod_variable': 'MTIC2534', 'meaning': 'Outro website ou portal'},
 {'cod_variable': 'MTIC254',
  'meaning': 'Votação on line para orientar a tomada de decisão sobre políticas públicas, orçamento, etc.'},
 {'cod_variable': 'MTIC2541', 'meaning': 'Website ou portal da prefeitura'},
 {'cod_variable': 'MTIC2542',
  'meaning': 'Website ou portal de outro órgão público'},
 {'cod_variable': 'MTIC2543', 'meaning': 'Redes sociais'},
 {'cod_variable': 'MTIC2544', 'meaning': 'Outro website ou portal'},
 {'cod_variable': 'MTIC255',
  'meaning': 'Não disponibilizou nenhuma das formas mencionadas acima'},
 {'cod_variable': 'MTIC261',
  'meaning': 'Bilhete ou cartão eletrônico aos cidadãos para uso de transporte público'},
 {'cod_variable': 'MTIC262',
  'meaning': 'Ônibus municipais com dispositivo de GPS que envia informações de localização e velocidade dos veículos'},
 {'cod_variable': 'MTIC263', 'meaning': 'Centro de controle operacional'},
 {'cod_variable': 'MTIC264',
  'meaning': 'Sistema de iluminação inteligente que permite a medição de consumo de energia ou alteração à distância da iluminação de áreas do município'},
 {'cod_variable': 'MTIC265',
  'meaning': 'Semáforos inteligentes controlados a distância para ações como priorizar o transporte público ou a circulação em rotas expressas'},
 {'cod_variable': 'MTIC266',
  'meaning': 'Sensores para monitoramento de áreas com risco de enchentes, alagamentos ou outros desastres naturais'},
 {'cod_variable': 'MTIC271', 'meaning': 'Portal da transparência'},
 {'cod_variable': 'MTIC272', 'meaning': 'Portal de dados abertos'},
 {'cod_variable': 'MTIC273', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC281',
  'meaning': 'Permitem navegação por todos os itens interativos da página sem necessidade do mouse'},
 {'cod_variable': 'MTIC282',
  'meaning': 'Permitem ao usuário de tecnologia assistiva saltar itens repetidos na página'},
 {'cod_variable': 'MTIC283', 'meaning': 'Descrevem conteúdo das imagens'},
 {'cod_variable': 'MTIC284', 'meaning': 'Inclui tradução para LIBRAS'},
 {'cod_variable': 'MTIC285',
  'meaning': 'Descrevem o conteúdo das páginas com o texto que aparece na aba do navegador'},
 {'cod_variable': 'MTIC286', 'meaning': 'Usam CAPTCHA para solicitações'},
 {'cod_variable': 'MTIC287', 'meaning': 'Nenhuma das alternativas'},
 {'cod_variable': 'MTIC288',
  'meaning': 'Não possui página na internet e/ou serviços eletrônicos'},
 {'cod_variable': 'MTIC289', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC29',
  'meaning': 'Modelo de acessibilidade usado no website ou portal'},
 {'cod_variable': 'MTIC30',
  'meaning': 'Estrutura organizacional para a área de educação - existência'},
 {'cod_variable': 'MTIC321',
  'meaning': 'Funcionários efetivos da própria prefeitura'},
 {'cod_variable': 'MTIC322',
  'meaning': 'Servidores cedidos de outro órgão público (cedidos da administração indireta ou de outra esfera pública)'},
 {'cod_variable': 'MTIC323', 'meaning': 'Estagiários'},
 {'cod_variable': 'MTIC324',
  'meaning': 'Cargo(s) comissionado(s) de livre nomeação'},
 {'cod_variable': 'MTIC325', 'meaning': 'Terceirizados'},
 {'cod_variable': 'MTIC326', 'meaning': 'Consultores'},
 {'cod_variable': 'MTIC327', 'meaning': 'Outros'},
 {'cod_variable': 'MTIC328', 'meaning': 'Não sabe'},
 {'cod_variable': 'MTIC33',
  'meaning': 'Carreira ou cargo específico de comunicação social (Cargo efetivo de provimento por concurso público exclusivo da área) - existência na estrutura'},
 {'cod_variable': 'MTIC341',
  'meaning': 'Disseminação da aplicação da Lei de acesso à informação (LAI) e orientações de como o município pode atender a população'},
 {'cod_variable': 'MTIC342',
  'meaning': 'Disseminação da aplicação da Lei geral de proteção de dados pessoais (LGPD) e orientações para a população de como o município cumpre a LGPD'},
 {'cod_variable': 'MTIC343',
  'meaning': 'Disseminação de canais de acesso e facilidades de atendimento para a população'},
 {'cod_variable': 'MTIC344',
  'meaning': 'Disseminação de planos de emergência e prevenção de riscos que afetam a população'},
 {'cod_variable': 'MTIC345',
  'meaning': 'Gerenciamento de canais de comunicação para a divulgação e prestação de contas da gestão municipal'},
 {'cod_variable': 'MTIC346',
  'meaning': 'Gestão ou participação nos canais de atendimento direto à população (solicitação de serviço, reclamações, etc.)'},
 {'cod_variable': 'MTIC347',
  'meaning': 'Serviços tradicionais de comunicação (publicidade, relações públicas, assessoria de impressa, conteúdos internet, eventos, etc.)'},
 {'cod_variable': 'MTIC348', 'meaning': 'Nenhuma das funções citadas'},
 {'cod_variable': 'MTIC349', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC35',
  'meaning': 'Licitações para contratar serviços de comunicação - execução'},
 {'cod_variable': 'MTIC3511', 'meaning': 'Publicidade'},
 {'cod_variable': 'MTIC3512', 'meaning': 'Promoção de eventos'},
 {'cod_variable': 'MTIC3513',
  'meaning': 'Assessoria de imprensa e divulgação'},
 {'cod_variable': 'MTIC3514', 'meaning': 'Produção de fotos'},
 {'cod_variable': 'MTIC3515', 'meaning': 'Produção de vídeos'},
 {'cod_variable': 'MTIC3516', 'meaning': 'Produção de produtos para o rádio'},
 {'cod_variable': 'MTIC3517',
  'meaning': 'Produção de produtos para a televisão'},
 {'cod_variable': 'MTIC3518', 'meaning': 'Gestão do site'},
 {'cod_variable': 'MTIC3519', 'meaning': 'Atuação na web e redes sociais'},
 {'cod_variable': 'MTIC35110', 'meaning': 'Nenhum dos serviços citados'},
 {'cod_variable': 'MTIC35111', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC361', 'meaning': 'Licitação por pregão eletrônico'},
 {'cod_variable': 'MTIC362',
  'meaning': 'Licitação por edital técnico e preço'},
 {'cod_variable': 'MTIC363',
  'meaning': 'Licitação com dispensa de inexibilidade'},
 {'cod_variable': 'MTIC364', 'meaning': 'Concorrência'},
 {'cod_variable': 'MTIC365', 'meaning': 'Tomada de preços'},
 {'cod_variable': 'MTIC366', 'meaning': 'Convite'},
 {'cod_variable': 'MTIC367', 'meaning': 'Nenhuma das modalidades citadas'},
 {'cod_variable': 'MTIC368', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MTIC37',
  'meaning': 'Canal de televisão, de rádio, ou qualquer outro conteúdo áudio visual no Youtube ou outra plataforma - manutençaõ pelo governo municipal'},
 {'cod_variable': 'MTIC381', 'meaning': 'Propaganda'},
 {'cod_variable': 'MTIC382', 'meaning': 'Organização de eventos'},
 {'cod_variable': 'MTIC383', 'meaning': 'Impulsionamento nas mídias sociais'},
 {'cod_variable': 'MTIC384', 'meaning': 'Divulgação jornalística'},
 {'cod_variable': 'MTIC385',
  'meaning': 'Não tem orçamento destinado a comunicação'},
 {'cod_variable': 'MTIC386', 'meaning': 'Nenhum dos itens citados'},
 {'cod_variable': 'MTIC387', 'meaning': 'Não sabe informar'},
 {'cod_variable': 'MGOV01',
  'meaning': 'Legislação municipal específica que estabeleça procedimentos e providências para garantir o direito de acesso à informação pública em conformidade com a Lei de Acesso à Informação - existência'},
 {'cod_variable': 'MGOV011a', 'meaning': 'Lei de criação'},
 {'cod_variable': 'MGOV011b', 'meaning': 'Ano de criação'},
 {'cod_variable': 'MGOV0121', 'meaning': 'Diário oficial impresso'},
 {'cod_variable': 'MGOV0122', 'meaning': 'Diário oficial internet'},
 {'cod_variable': 'MGOV021',
  'meaning': 'Estabelece prazo de atendimento de pedido de acesso à informação pública igual ou inferior a 20 dias corridos'},
 {'cod_variable': 'MGOV022',
  'meaning': 'Institui procedimentos de classificação de informação sigilosa em âmbito municipal'},
 {'cod_variable': 'MGOV023',
  'meaning': 'Prevê autoridade de monitoramento para implementação da Lei de Acesso à Informação pública'},
 {'cod_variable': 'MGOV024',
  'meaning': 'Prevê órgão central de monitoramento das ações relativas ao acesso à informação pública'},
 {'cod_variable': 'MGOV025',
  'meaning': 'Prevê a divulgação de relatório de monitoramento com informações estatísticas dos pedidos de acesso à informação pública'},
 {'cod_variable': 'MGOV026',
  'meaning': 'Prevê mais de uma instância recursal interna ao órgão ou entidade demandada'},
 {'cod_variable': 'MGOV027',
  'meaning': 'Estabelece instância recursal autônoma e independente em relação à autoridade que proferiu a decisão impugnada'},
 {'cod_variable': 'MGOV028',
  'meaning': 'Estabelece procedimento em caso de omissão de resposta a pedidos de informação pública'},
 {'cod_variable': 'MGOV031',
  'meaning': 'Local com condições para atender e orientar o público quanto ao acesso a informações públicas'},
 {'cod_variable': 'MGOV032', 'meaning': 'Internet'},
 {'cod_variable': 'MGOV033', 'meaning': 'Telefone'},
 {'cod_variable': 'MGOV034', 'meaning': 'Carta'},
 {'cod_variable': 'MGOV035', 'meaning': 'Outro'},
 {'cod_variable': 'MGOV036', 'meaning': 'Não disponibiliza'},
 {'cod_variable': 'MGOV04',
  'meaning': 'Solicitações de acesso à informação em 2023 com base na Lei de acesso à informação (LAI)'},
 {'cod_variable': 'MGOV05',
  'meaning': 'A prefeitura publica, para acesso público, perguntas e respostas feitas através da Lei de acesso à informação (LAI)'},
 {'cod_variable': 'MGOV06',
  'meaning': 'Disponibilização de informações pormenorizadas sobre execução orçamentária e financeira (em atendimento à Lei Complementar 131/2009)'},
 {'cod_variable': 'MGOV061',
  'meaning': 'Disponibiliza informações em tempo real'},
 {'cod_variable': 'MGOV0621', 'meaning': 'Página na internet'},
 {'cod_variable': 'MGOV0622', 'meaning': 'Portal transparência'},
 {'cod_variable': 'MGOV0623', 'meaning': 'Outro website'},
 {'cod_variable': 'MGOV0711', 'meaning': 'Em CVS, ODS, XLS, DOC'},
 {'cod_variable': 'MGOV0712', 'meaning': 'Em PDF ou imagem'},
 {'cod_variable': 'MGOV0713', 'meaning': 'Em outro tipo de arquivo'},
 {'cod_variable': 'MGOV0715', 'meaning': 'Não publica'},

In [0]:
# Transform on Dataframe
df_meta_vars = pd.DataFrame(ws_meta_vars)

In [0]:
df_meta_vars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cod_variable  358 non-null    object
 1   meaning       358 non-null    object
dtypes: object(2)
memory usage: 5.7+ KB

In [0]:
# Convert the value from the columns to String and keep them clean
df_meta_vars['cod_variable'] = df_meta_vars['cod_variable'].astype(str).str.strip().str.upper()
df_meta_vars['meaning'] = df_meta_vars['meaning'].astype(str).str.strip()

In [0]:
df_meta_vars.iloc[0]

cod_variable    MTIC011
meaning         Correio
Name: 0, dtype: object

In [0]:
df_meta_vars.iloc[357]

cod_variable                                               MGOV36
meaning         Regulamentação ou lei municipal específica sob...
Name: 357, dtype: object

# Pre-Processing the data

In [0]:
df_data.head()

   Cod Munic Uf_x  Cod Uf_x  ...             Mgov34  Mgov35 Mgov36
0    1100015   RO        11  ...                Não     Não    Não
1    1100023   RO        11  ...                Sim     Sim    Sim
2    1100031   RO        11  ...                Não     Sim    Sim
3    1100049   RO        11  ...  Não sabe informar     Não    Não
4    1100056   RO        11  ...                Não     Não    Não

[5 rows x 373 columns]

In [0]:
df_info_ws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Columns: 205 entries, Cod Munic to Mtic387
dtypes: int64(3), object(202)
memory usage: 8.7+ MB

In [0]:
x = 0
for column in df_data.columns:
    print(column, end="\t\t")
    x += 1
    if (x % 7 == 0):
        print("\n")

Cod Munic		Uf_x		Cod Uf_x		Desc Mun_x		Populacao_x		Faixa_populacao_x		Regiao_x

Mtic011		Mtic012		Mtic013		Mtic014		Mtic015		Mtic016		Mtic017

Mtic018		Mtic04		Mtic06		Mtic071		Mtic072		Mtic073		Mtic074

Mtic075		Mtic076		Mtic077		Mtic078		Mtic08		Mtic091		Mtic092

Mtic093		Mtic10		Mtic11		Mtic12a1		Mtic12a2		Mtic12a3		Mtic12a4

Mtic12a5		Mtic12a6		Mtic12a7		Mtic12a8		Mtic12b1		Mtic12b2		Mtic12b3

Mtic12b4		Mtic12b5		Mtic12b6		Mtic12b7		Mtic12b8		Mtic12b9		Mtic12b10

Mtic12b11		Mtic12b12		Mtic12b13		Mtic12b14		Mtic131		Mtic132		Mtic133

Mtic134		Mtic135		Mtic136		Mtic137		Mtic138		Mtic139		Mtic141

Mtic142		Mtic143		Mtic144		Mtic145		Mtic146		Mtic15		Mtic161

Mtic162		Mtic163		Mtic164		Mtic165		Mtic166		Mtic167		Mtic171

Mtic172		Mtic173		Mtic174		Mtic175		Mtic176		Mtic181		Mtic182

Mtic183		Mtic184		Mtic185		Mtic186		Mtic18a1		Mtic18a2		Mtic18a3

Mtic18a4		Mtic18a5		Mtic18a6		Mtic19		Mtic201		Mtic202		Mtic203

Mtic204		Mtic205		Mtic206		Mtic211		Mtic212		Mtic213		Mtic214

Mtic215		Mtic216		Mtic217		Mtic22		Mtic23		Mtic241		Mtic242

Mtic2421		Mtic243		Mtic2431		Mtic244		Mtic251		Mtic2511		Mtic2512

Mtic2513		Mtic2514		Mtic252		Mtic2521		Mtic2522		Mtic2523		Mtic2524

Mtic253		Mtic2531		Mtic2532		Mtic2533		Mtic2534		Mtic254		Mtic2541

Mtic2542		Mtic2543		Mtic2544		Mtic255		Mtic261		Mtic262		Mtic263

Mtic264		Mtic265		Mtic266		Mtic271		Mtic272		Mtic273		Mtic281

Mtic282		Mtic283		Mtic284		Mtic285		Mtic286		Mtic287		Mtic288

Mtic289		Mtic29		Mtic30		Mtic31		Mtic321		Mtic322		Mtic323

Mtic324		Mtic325		Mtic326		Mtic327		Mtic328		Mtic33		Mtic331

Mtic341		Mtic342		Mtic343		Mtic344		Mtic345		Mtic346		Mtic347

Mtic348		Mtic349		Mtic35		Mtic3511		Mtic3512		Mtic3513		Mtic3514

Mtic3515		Mtic3516		Mtic3517		Mtic3518		Mtic3519		Mtic35110		Mtic35111

Mtic361		Mtic362		Mtic363		Mtic364		Mtic365		Mtic366		Mtic367

Mtic368		Mtic37		Mtic381		Mtic382		Mtic383		Mtic384		Mtic385

Mtic386		Mtic387		Uf_y		Cod Uf_y		Desc Mun_y		Populacao_y		Faixa_populacao_y

Regiao_y		Mgov01		Mgov011a		Mgov011b		Mgov0121		Mgov0122		Mgov021

Mgov022		Mgov023		Mgov024		Mgov025		Mgov026		Mgov027		Mgov028

Mgov031		Mgov032		Mgov033		Mgov034		Mgov035		Mgov036		Mgov04

Mgov05		Mgov06		Mgov061		Mgov0621		Mgov0622		Mgov0623		Mgov0711

Mgov0712		Mgov0713		Mgov0715		Mgov0721		Mgov0722		Mgov0723		Mgov0725

Mgov0731		Mgov0732		Mgov0733		Mgov0735		Mgov0741		Mgov0742		Mgov0743

Mgov0745		Mgov0751		Mgov0752		Mgov0753		Mgov0755		Mgov0761		Mgov0762

Mgov0763		Mgov0765		Mgov0771		Mgov0772		Mgov0773		Mgov0775		Mgov081

Mgov082		Mgov083		Mgov084		Mgov085		Mgov086		Mgov087		Mgov088

Mgov089		Mgov0810		Mgov0811		Mgov09		Mgov091		Mgov092a		Mgov092b

Mgov10		Mgov111		Mgov112		Mgov113		Mgov114		Mgov115		Mgov116

Mgov13		Mgov141		Mgov142		Mgov15		Mgov16		Mgov17		Mgov171

Mgov172		Mgov181		Mgov182		Mgov183		Mgov184		Mgov185		Mgov186

Mgov187		Mgov188		Mgov189		Mgov1810		Mgov1811		Mgov1812		Mgov1813

Mgov1814		Mgov1815		Mgov1816		Mgov1817		Mgov1818		Mgov191		Mgov192

Mgov193		Mgov194		Mgov195		Mgov196		Mgov201		Mgov202		Mgov203

Mgov204		Mgov211		Mgov212		Mgov213		Mgov221		Mgov222		Mgov223

Mgov224		Mgov23		Mgov241		Mgov242		Mgov243		Mgov244		Mgov245

Mgov246		Mgov247		Mgov248		Mgov251		Mgov252		Mgov253		Mgov254

Mgov255		Mgov26		Mgov261a		Mgov261b		Mgov261c		Mgov262		Mgov271

Mgov272		Mgov273		Mgov274		Mgov28		Mgov29		Mgov301		Mgov302

Mgov303		Mgov31		Mgov3111		Mgov3112		Mgov3113		Mgov3114		Mgov3115

Mgov3116		Mgov3117		Mgov3118		Mgov3119		Mgov32		Mgov33		Mgov34

Mgov35		Mgov36